using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace L2_LoginForm
{
    public partial class SearchingStudentList : Form
    {
        STUDENT student = new STUDENT();
        public SearchingStudentList(string searchText)
        {
            InitializeComponent();
            SearchStudent(searchText);

        }

        private void SearchingStudentList_Load(object sender, EventArgs e)
        {
            // Load data into DataSet (auto-generated by designer)
            this.stdTableAdapter.Fill(this.qLSVDBDataSet1.std);

            // Make DataGridView ReadOnly to prevent editing
            dataGridView.ReadOnly = true;

            // Prevent user from adding rows
            dataGridView.AllowUserToAddRows = false;

            // Set row height for better image display
            dataGridView.RowTemplate.Height = 100;

            // Handle picture column (assume it's column index 7)
            DataGridViewImageColumn picCol = (DataGridViewImageColumn)dataGridView.Columns[7];
            picCol.ImageLayout = DataGridViewImageCellLayout.Zoom; // Zoom to fit and keep aspect ratio

            // Optional: Adjust columns to fit content nicely
            dataGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; // Fill width evenly
            dataGridView.Columns[0].AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells; // ID column to fit content
            dataGridView.Columns[1].AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells; // First Name
            dataGridView.Columns[2].AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells; // Last Name
            dataGridView.Columns[3].AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells; // DoB
            dataGridView.Columns[4].AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells; // Gender
            dataGridView.Columns[5].AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells; // Phone Number
            dataGridView.Columns[6].AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;     // Address fills remaining space
            dataGridView.Columns[7].Width = 100; // Set fixed width for picture

            // Optional: Align text to middle for better look
            dataGridView.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
            dataGridView.ColumnHeadersDefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
        }


        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }
        private void SearchStudent(string searchText)
        {
            SqlCommand command = new SqlCommand("SELECT * FROM std " +
                                                "WHERE fname LIKE @search OR lname LIKE @search OR phone LIKE @search OR address LIKE @search");
            command.Parameters.Add("@search", SqlDbType.VarChar).Value = "%" + searchText + "%";

            // Bind the result to the DataGridView
            dataGridView.DataSource = student.getStudents(command);
        }
    }
}
